### ISSUE TITLE
Test killed by timeout

### ISSUE THREAD

**Issue by zbigg** [zbigg/mocha-webdriver-runner#7]
Sporadically, test run timeouts in CI.
In our environment, it's sometimes even 1/3 of runs.

Synopsis

```
00:01:50.795     ✓ some test ... (169ms)

 ^^^^^^ stucks for 5 minutes
 vvvvvv unhandled timeout somewhere in selenium webdriver not caught 
00:06:50.840 (node:413) UnhandledPromiseRejectionWarning: TimeoutError: timeout
00:06:50.841   (Session info: headless chrome=76.0.3809.100)
00:06:50.841     at Object.throwDecodedError (//home/foo/bar/node_modules/selenium-webdriver/lib/error.js:550:15)
00:06:50.842     at parseHttpResponse (//home/foo/bar/node_modules/selenium-webdriver/lib/http.js:563:13)
00:06:50.843     at Executor.execute (//home/foo/bar/node_modules/selenium-webdriver/lib/http.js:489:26)
00:06:50.844     at process._tickCallback (internal/process/next_tick.js:68:7)
00:06:50.844 (node:413) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
00:06:50.846 (node:413) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
^^^ mocha-webdriver-runner exits with non-zero exit code


```

Environment
 - Chrome (headless) 76 / Linux
 - `mocha-webdriver-runner` 0.5.3 (current) / Linux
 - Node.JS 10.16.3
Test runs against `--headless-chrome`

**Comment by zbigg** [comment]
Looks like tests were too big to fit into default memory configuration of Chrome in docker.

As workaround, we've added `--disable-dev-shm-usage" option as mentioned here: https://github.com/puppeteer/puppeteer/issues/1834

Example:
```
-C goog:chromeOptions.args='["--headless", "--disable-gpu=true", "--no-sandbox", "--disable-dev-shm-usage", "--window-size=1280,800"]' \
```
